Fix python codestyle
jupyter/docker-stacks pull request #1118
Opened 2020-06-25 17:44 UTC by mathbunnyru

2020-06-27 15:55 UTC, mathbunnyru commented
Ok, I used flake8 to check all the files, because I'm familiar with it.
So, if you don't mind, I'll add it first in a pre-commit, like you suggested.

Then, if I feel comfortable adding Black, I will also add it, but in a separate review.

Hope this is ok?

2020-06-27 15:57 UTC, mathbunnyru commented
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
Seems to be good article to start with

2020-06-29 19:27 UTC, romainx commented
@mathbunnyru It's Ok to use another formatter. The main idea is to enforce formatting by a hook in order to keep code consistent. I only suggested Black because it has some interesting features and one of the best is summarized by

> Black is opinionated so you don’t have to be.

So please go ahead with flake8 if your more confortable.

Many thanks for your help.
Best.

2020-07-04 17:13 UTC, mathbunnyru commented
I tried to look at pre-commit module, but it seems to have a problem - it is still a pre-commit hook.
It means that if user doesn't install it, then nothing will be checked.

And we want to check all the files, server-side - this is the only way to ensure, that everything passes codestyle.

So I added one simple Makefile step, which is included in `lint-all` and `lint-build-test-all` stages.

Please, let me know what you think about this approach.

2020-07-11 14:04 UTC, romainx commented
Hello @mathbunnyru.
Sorry for my late answer. 

I think your solution is good to check at server-side before merging a PR if the code is formatted. So let's keep it.

However I still think that the use of [pre-commit](https://pre-commit.com/) is a good solution that can be used in addition to the server side check. The advantage is that the hook is run at each commit and users will not forget to format the file before committing. It will avoid a failure in checks at server side that will lead to unnecessary iterations. My fear is that adding only a server-side check without the pre-commit counterpart will lead to rejected PR.

Maybe I could draft it to add a hook for the hadolint check #1100 ?

2020-07-12 15:40 UTC, mathbunnyru commented
Thanks @romainx 👍 
I took a look in change https://github.com/jupyter/docker-stacks/pull/1123 and asked for some changes to make it easier to adapt in the future.
We should merge you pre-commit hook first, and then deal with this review.

2020-08-16 17:11 UTC, mathbunnyru commented
`pre-commit run --all-files flake8` seems to pass.
If I make some script ugly, then I get a fail, so everything seems to work.

2020-08-17 14:38 UTC, mathbunnyru commented
@romainx @parente could you please take a look?

2020-09-01 06:42 UTC, romainx commented
@mathbunnyru Sorry I don't have too much time right now, I will take a look asap.

2020-09-25 04:05 UTC, mathbunnyru commented
@romainx any chance you will take a look or should I close the PR?

To be honest, waiting for such a long time makes me sad about creating new PRs and doing some work for this project😔

2020-09-25 04:16 UTC, romainx commented
@mathbunnyru sad to hear that 😢. Sorry but I did not take the time to review that. I will try to do it. However I do not have so much time and I'm trying to focus on user facing features / bugs. I though it was a long term internal improvement and postponed this review. 
I will try to do it this weekend.
My intend was not to discourage you for submitting such useful PR. So please forgive my lack of answer and keep contributing to this project 😊.

2020-09-25 04:18 UTC, mathbunnyru commented
Thanks, @romainx ☺️

2020-09-25 08:45 UTC, romainx requested changes
Hello,

The addition of the [autopep8 hook](https://github.com/pre-commit/mirrors-autopep8) will permit to automatically fix errors.

For example. 

- Add blank lines in `test_pandoc.py` to trigger an error.
- Stage the file for commit.
- Trigger a first run of `pre-commit`.

```bash
$ pre-commit run                                                                              

# [...]
# flake8...................................................................Failed
# - hook id: flake8
# - exit code: 1
# 
# base-notebook/test/test_pandoc.py:17:1: W293 blank line contains whitespace
# base-notebook/test/test_pandoc.py:18:5: E303 too many blank lines (3)
# 
# autopep8.................................................................Failed
# - hook id: autopep8
# - files were modified by this hook
# [...]
```
The formatting issue is detected by `flake8` **and fixed by `autopep8`**.

- Stage the modified file for commit.
- Trigger again the run of `pre-commit`.

```bash
$ pre-commit run                                                                              

flake8...................................................................Passed
autopep8.................................................................Passed
```

All good now!

Could you please perform this change.
After that I will merge it 🚀.

Many thanks for your help and sorry again for the delay 🐌 🐌.

2020-09-25 08:45 UTC, romainx commented on .pre-commit-config.yaml
>    - repo: local
Could you please add the [autopep8 hook](https://github.com/pre-commit/mirrors-autopep8)

```YAML 
 - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
```

2020-09-25 21:27 UTC, parente commented
Thank you @mathbunnyru for the PR and @romainx for taking the time to review it. I appreciate both of your efforts. My availability to contribute here ebbs and flows too, and I think that's OK. We will review and merge PRs that benefit the project, even if not as quickly as some of the larger, more active Jupyter projects.

2020-09-26 19:18 UTC, romainx commented
@mathbunnyru I can also merge the PR as is and add `autopep8` through a follow-on PR. Tell me what you prefer.
Thanks

2020-09-26 20:30 UTC, mathbunnyru commented
I'm totally OK with both scenarios.
I have some days off till Monday, so I won't be able to add autopep8 this Saturday and Sunday.

2020-09-27 04:46 UTC, romainx commented
Ok @mathbunnyru no problem I've waited more than one month before reviewing it, so I can wait a couple of days 😆 
Take the necessary time to do it.

2020-09-28 03:40 UTC, mathbunnyru commented
Merge latest master

2020-09-28 03:44 UTC, mathbunnyru commented
Added autopep8.

I think everything should be good to go.

2020-09-28 17:34 UTC, romainx approved these changes
Perfect.
Thank you for all the work done 🍰 and for your patience 😊 
Good to go 🚀

2020-09-28 17:35 UTC, merged