Add SensiML notebook, based on TensorFlow notebook
jupyter/docker-stacks pull request #1234
Opened 2021-02-08 16:57 UTC by jublin

2021-02-18 04:25 UTC, romainx commented
Hello @jublin ,


Sorry for the late answer and thanks for this PR. However we are sorry but we are not extending the core stack with new images, that takes instead the [community images path][1]. Here is a recent comment explaining this process.

> We've been requesting that all new image definitions take the [community images path][1], primarily because this repository is unwieldy and we're already finding it difficult to maintain the images that already exist here. It sounds like you already have a nice project setup for building the images. Would you be open to [submitting a pull request linking to it from the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks) instead of this PR?

Another solution is to integrate from this PR only the "recipe" part.
So if you agree, we could merge the recipe you wrote in `recipes.md` explaining how to build a `sensiml-notebook` image from the `tensorflow-notebook` image. If it's Ok for you, you can modify your PR to include only this description. 

Please keep us informed of what you want to do between both solutions.

Best.

[1]: https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html

2021-03-17 20:27 UTC, romainx requested changes
Hello @jublin,

Do you want to change your PR to keep only the `recipes.md` and I will merge it? In the other case I will close it for the reasons mentioned in my previous comment.

Many thanks

2021-05-06 23:37 UTC, mathbunnyru requested changes
@jublin are you still interested in merging this?

Please, take a look at the comment above and after the change proposed this will be a good recipe for the community.

If not, please, close the PR.

2021-05-06 23:37 UTC, mathbunnyru commented on docs/using/recipes.md
> +
```suggestion
```

2021-05-23 23:16 UTC, consideRatio commented
Given previous comments, I'll go ahead and close this PR at this point.

2021-05-23 23:16 UTC, closed without merging