Add datascience-python-r-notebook
jupyter/docker-stacks pull request #1569
Opened 2022-01-12 13:48 UTC by massongit

fix https://github.com/jupyter/docker-stacks/issues/1551

I add `datascience-python-r-notebook`, which is a multi-architecture stack based on `jupyter/datascience-notebook` without Julia.
If it add, users who do not use Julia will be able to use `jupyter/datascience-notebook` on M1 Mac and latest Docker Desktop for Mac.

2022-01-20 18:18 UTC, mathbunnyru requested changes
Also https://github.com/jupyter/docker-stacks/blob/master/docs/using/selecting.md#image-relationships has to be upgraded.

To be honest, I don't think adding new image is what we should do.
I do understand, that you want the image to work under arm, but the better approach would be to fix our build system to use native arm runners.
It's difficult, but it's worth it.

2022-01-20 18:37 UTC, consideRatio requested changes
I'm strongly opposed to adding another image to this repo. If we should do that, I think we should first have clear guidelines on when and why we do decide to add another images. My opposition stems from a care of this projects long term maintainability, not that the addition has no value for an end user.

I've seen several open source projects run into trouble for accepting more and more variations of something when there are infinite amounts of variations possible. I think they all need to say stop after a while as it becomes unsustainable to keep adding new parts.

@romainx @mathbunnyru what do you think?

2022-01-20 19:39 UTC, closed without merging

2022-01-20 23:56 UTC, massongit commented
Thank you for your reviews!
I agree that this approach is not good for maintainability.
I would like to cooperate as much as possible to find to install Julia under ARM.

2022-01-21 08:43 UTC, benz0li commented
@massongit You may be interested in https://gitlab.b-data.ch/jupyterlab/r/docker-stack, which combines https://github.com/rocker-org/rocker-versioned with https://github.com/jupyter/docker-stacks (± minimal-notebook) including [code-server](https://github.com/coder/code-server) and further customisations.

See also https://demo.jupyter.b-data.ch for a minimal deployment (CPU: 2 cores, RAM: 4 GB) based on https://gitlab.com/b-data/docker/deployments/jupyter serving either [registry.gitlab.b-data.ch/jupyterlab/r/verse:latest-root](https://gitlab.b-data.ch/jupyterlab/r/verse/container_registry) or [registry.gitlab.b-data.ch/jupyterlab/julia/ver:latest-root](https://gitlab.b-data.ch/jupyterlab/julia/ver/container_registry).  
ℹ️ Both [JupyterHub](https://gitlab.b-data.ch/jupyterhub/jupyterhub/container_registry) and JupyterLab images are multi-arch (`linux/amd64`, `linux/arm64/v8`), the latter Debian-based.

Both JupyterLab images have _stock_ Python (currently v3.9.2) installed and focus on Julia and R, respectively. Thus, apart from `jupyter-server-proxy jupyterhub jupyterlab jupyterlab-git notebook nbconvert [radian]` and its dependencies, no further Python packages are installed.