Add version args to base-notebook dockerfile
jupyter/docker-stacks pull request #1574
Opened 2022-01-19 03:56 UTC by asdfsx

To install specific notebook/jupyterhub/jupyterlab into base-notebook image, add version args to dockerfile

2022-01-19 13:54 UTC, mathbunnyru requested changes

2022-01-19 13:54 UTC, mathbunnyru commented on base-notebook/Dockerfile
> +ARG JUPYTERLAB_VERSION=default
If we change default values to empty strings, then the check is not needed and we can just write
```
mamba install --quiet --yes notebook="${NOTEBOOK_VERSION}"
```

And if someone specified version, they will get it and if not - they will get default version.

2022-01-19 14:08 UTC, consideRatio commented
This is a slippery slope, why not allow configuration of another software version as well if we allow these three to be configurable?

I suggest to reject thus PR, the workaround of building from an already built image and installing a specific version doesnt seem to cause much downside to me.

Another option would be to perhaps declare version restrictions in conda before it resolves things, then the user could provide any kind of restriction without us having to have logic hardcoded for individual packages etc.

2022-01-19 14:12 UTC, mathbunnyru commented
What @consideRatio tells makes a lot of sense to me.
Both his options seem reasonable and building from an existing image in my opinion is much easier than rebuilding the whole stack with some environment variables set.

2022-01-21 03:33 UTC, asdfsx commented
I'm trying to build a base-notebook image with specific version.   
And I found there is a variable to specific PYTHON version, so I add these 3 variables.

Maybe I should just using the existing notebook and reinstall jupyterlab and jupyterhub with other version.

2022-01-21 10:09 UTC, mathbunnyru commented
Yes, it would be a better choice.

2022-01-21 10:09 UTC, closed without merging