add the COPY_HOME option in start.sh
jupyter/docker-stacks pull request #1637
Opened 2022-02-25 10:16 UTC by djangoliv

These changes make it possible to force the copy of the files of jovyan user to NB_USER

2022-02-25 10:39 UTC, consideRatio commented
This feature has been raised for discussion already in https://github.com/jupyterhub/kubespawner/issues/574#issuecomment-1048706438. I wrote the following that I think remains relevant.

>This is a discussion related to jupyter/docker-stacks. My understanding is that you discuss the following feature summarized.
>
>1. You have ensured there is a `/home/{username}/some_dir` ahead of time
>2. As part of the `start.sh` script of jupyter/docker-stacks runs, you have made it switch from a `jovyan` user to `{username}`. As part of this script running, you want to be able to make `start.sh` change its default behavior when the `{username}` home folderexists. You want either to replace the `{username}` folder if it exists, or in some way merge content from `jovyan` home folder to the existing `{username}` folder.
>
>I would overall say that this is a quite uncommon action, and could easily lead to loss of data if misunderstood by someone. Due to that, I'm not so happy about the idea of supporting a feature like that - if I understood it correctly.

---

> Oh... I couldn't transfer this issue to jupyter/docker-stacks as it was outside the organization. Anyhow, that is where this belongs. You could perhaps copy paste things from this to there if you want to raise it for discussion? Please if so, also include my response.

---

I don't think this feature should be implemented as I think it isn't an intuitive enough user experience, and I believe it could lead to confusion and loss of data - besides adding to a long term maintenance complexity.

2022-02-25 11:26 UTC, djangoliv commented
@consideRatio Sorry for the noise on kubespawner issues.

It is obviously not up to kubespawner to handle this use case.

But in docker-stacks this feature is already implemented in start.sh . This PR is just a fix for a special case.

I agree that renaming the user and their files may seem dangerous, but keeping the username in jupyterhub is very comfortable.

2022-03-08 20:48 UTC, mathbunnyru requested changes
I'm not an expert on how `start.sh` works in different cases and I trust @consideRatio's opinion on this one.

2022-03-08 20:48 UTC, mathbunnyru commented on base-notebook/start.sh
> +        if [[ ! -e "/home/ogiorgis"  ||  "${COPY_HOME}" == "yes" || "${COPY_HOME}" == "1" ]]; then
`ogiorgis` was probably the name of your user and it should be changed.
And there are too many spaces near `||`.

2022-03-08 20:48 UTC, mathbunnyru commented on base-notebook/start.sh
> +    # - COPY_HOME: a boolean ("1" or "yes") to copy the otiginal home files
```suggestion
    # - COPY_HOME: a boolean ("1" or "yes") to copy the original home files
```

2022-03-08 20:48 UTC, mathbunnyru commented on docs/using/troubleshooting.md
> +   - `-e COPY_HOME=yes`: ensure that the new user will have the same files than the old user in its `/home` directory
```suggestion
   - `-e COPY_HOME=yes`: ensure that the new user will have the same files as the old user in its `/home` directory
```

2022-03-09 07:36 UTC, consideRatio commented
I want to avoid mixed signals of both reviewing with code suggestions and saying the feature is problematic to accept, so i'll close this PR for now.

Not because this feature doesn't have value at least to you, but because of what was mentioned above.

2022-03-09 07:36 UTC, closed without merging