Adding list of groups to `${NB_USER}`
jupyter/docker-stacks pull request #1725
Opened 2022-06-14 10:27 UTC by IslamAlam

## Describe your changes
A useful feature for adding a list of groups to `${NB_USER}` in the case of needing to read multiple volumes with different access rights. For instance, it is handy to add a user to groups given from ActiveDirectory.
## Issue ticket if applicable

## Checklist (especially for first-time contributors)

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [x] I will try not to use force-push to make the review process easier for reviewers
- [x] I have updated the documentation for significant changes

2022-07-04 06:15 UTC, mathbunnyru commented
@IslamAlam the reason for that is because we use not freshly built images to use as a base image, but end up pulling old images from dockerhub.

2022-07-04 06:21 UTC, mathbunnyru requested changes
To be honest, I'm not sure we should add more stuff to our start scripts.
I mean, they are already over-complicated, not very well tested.

Have you tried using [Startup hooks](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) for your purposes?

2022-07-04 06:21 UTC, mathbunnyru commented on base-notebook/start.sh
> +        g_name="${g_name:0:32}"
I don't think we should manipulate user's input this way.
If they use long group name and it fails when starting the container, it's actually better, than fixing the group name and making them believe everything is fine.

2022-07-04 06:21 UTC, mathbunnyru commented on base-notebook/start.sh
> +            eval 'usermod -a -G "${g_name:-"g_${g_id:?}"}" ${NB_USER}'
Why are we calling `eval` instead of calling these commands directly?

2022-07-05 18:34 UTC, mathbunnyru commented
> @IslamAlam the reason for that is because we use not freshly built images to use as a base image, but end up pulling old images from dockerhub.

This is merged in master. Please, merge `master` branch to your branch, to build images correctly.

2022-07-07 11:32 UTC, consideRatio commented
I think that this may be stretching the functionality that makes sense for jupyter/docker-stacks to maintain long term beyond what is reasonable.

I think [startup hooks](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) is the way to go for something more advanced like this.

2022-07-09 12:39 UTC, mathbunnyru commented
Closing this PR. Please, if you think this is relevant for many users, fix the issues, reopen PR and let's wait for other people to ask for this feature.

2022-07-09 12:39 UTC, closed without merging