add jupyterlab-git extension
jupyter/docker-stacks pull request #1895
Opened 2023-04-25 07:49 UTC by romeokienzler

## Describe your changes
add jupyterlab-git extension

New size of the image: 3.82GB

## Issue ticket if applicable

 Fix: #1464 

## Checklist (especially for first-time contributors)

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [x] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

2023-04-25 09:12 UTC, mathbunnyru requested changes

2023-04-25 09:12 UTC, mathbunnyru commented on scipy-notebook/Dockerfile
> +    'jupyterlab-git' && \
Let's keep this list sorted.

2023-04-25 09:13 UTC, mathbunnyru requested changes
You will also need to update the docs here: https://github.com/jupyter/docker-stacks/blob/main/docs/using/selecting.md#jupyterscipy-notebook

2023-04-25 13:00 UTC, romeokienzler commented on scipy-notebook/Dockerfile
> +    'jupyterlab-git' && \
@mathbunnyru pushed

2023-04-26 10:37 UTC, romeokienzler commented
@mathbunnyru added documentation

2023-04-26 10:39 UTC, mathbunnyru commented
@romeokienzler great 👍 
Please, do not forget to add an exception around here, because `jupyterlab-git` is not importable: https://github.com/jupyter/docker-stacks/blob/main/tests/base-notebook/test_packages.py#L72
This will fix CI tests.
You can also get familiar with how our tests work [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/tests.html)

2023-04-26 10:39 UTC, mathbunnyru requested changes
Waiting for tests fix.

2023-04-27 07:58 UTC, romeokienzler commented
Thanks @mathbunnyru, done

2023-04-27 09:01 UTC, mathbunnyru approved these changes
As this seems to be really popular package for jupyterlab, I think it makes sense to add it, so I'm ok with this change.

2023-04-27 10:49 UTC, merged