Add jupyter/julia-notebook
jupyter/docker-stacks pull request #1926
Opened 2023-06-26 22:21 UTC by yuvipanda

## Describe your changes

There is a growing number of Julia users in the Jupyter ecosystem who do not use R, and hence would <3 to have a dedicated docker image that doesn't bring in all the R stuff that datascience-notebook brings in! The built image size is much smaller, and eventually paves the way to better ecosystem support for Julia.

## Checklist (especially for first-time contributors)

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I will try not to use force-push to make the review process easier for reviewers
- [ ] I have updated the documentation for significant changes

2023-06-27 02:12 UTC, yuvipanda commented
This image is  2.2GB, vs the datascience-notebook being 5.83GB!

2023-06-27 08:29 UTC, mathbunnyru commented
Docs failing is fine.
`Pre-commit` mypy error is valid though:
```
tests/julia-notebook/test_julia.py: error: Duplicate module named "test_julia" (also at "tests/datascience-notebook/test_julia.py"
```

2023-06-27 08:37 UTC, mathbunnyru requested changes
There are a few things I would like to ask you to do:

1. In places, where images were sorted by name, let's keep them sorted.
2. In other places, let's put `julia-notebook` after `r-notebook`.
3. Please, update the [Makefile](https://github.com/jupyter/docker-stacks/blob/main/Makefile#L11)
4. And also, [inheritance diagram](https://github.com/jupyter/docker-stacks/blob/main/docs/using/selecting.md#image-relationships)

I also think, that it makes sense to put Julia installation in a bash script and to add it to `base-notebook` and then we will just run it in some images. This will allow us to reduce code duplication. This can be done in a separate PR later though, to make it easier for you.

2023-06-27 08:37 UTC, mathbunnyru commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - julia-notebook
Let's keep this list sorted.

2023-06-27 08:37 UTC, mathbunnyru commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +        - julia-notebook
This list is sorted as well.

2023-06-27 08:37 UTC, mathbunnyru commented on julia-notebook/README.md
> +# Jupyter Notebook Data Science Stack
Name has to be changed here.

2023-06-27 19:13 UTC, yuvipanda commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - julia-notebook
Done!

2023-06-27 19:13 UTC, yuvipanda commented on julia-notebook/README.md
> +# Jupyter Notebook Data Science Stack
Done

2023-06-27 19:13 UTC, yuvipanda commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +        - julia-notebook
Done!

2023-06-27 19:18 UTC, yuvipanda commented
Thanks for the quick review, @mathbunnyru! I have addressed everything except the inheritance diagram! Do you have a tool suggestion on what I can use to edit that?

2023-06-27 20:54 UTC, mathbunnyru commented
@yuvipanda take a look at the markdown, it's not just an SVG image, but also a link where you can change the diagram easily, generate new permanent link and download an image as a new SVG.
<http://interactive.blockdiag.com/?compression=deflate&src=eJyFjjFuwzAMRXefgvDUDDpAYaQnyNaOBQraphPCCmlIFIy0yN0rdQggI4XX9x__Z-91mEfGM_w0ACNNmLx9TSoW-ZvgCK9d5hqYxNBYJaNFgwVk65octalPYulTXk4f77CyXXLOYhDIE0Y6tODeYMwrFFw0HOboJk0y_rWV8v-yctfnBidq1KvORa5AMa4sfEVfSVtWvDjwcqusmhSnNZKoYfK6Pnj7XM0vYqYkA-1Oh53Z5RYXDHNlbVnx0Hu3Ne-_7MWcxg>

2023-06-27 22:40 UTC, yuvipanda commented
That's very helpful, @mathbunnyru! I think I've addressed them now.

2023-06-28 10:41 UTC, merged

2023-06-28 10:43 UTC, mathbunnyru commented
@yuvipanda I added a new repository to the DockerHub and merged your PR (that's all I had to do manually, even description will be pushed automatically to DockerHub 🙂).

I didn't congratulate you with the first PR to this repo, so let me congratulate you with the second one :heart:

2023-06-28 10:44 UTC, mathbunnyru commented
https://hub.docker.com/r/jupyter/julia-notebook

Images should be updated in ~2 hours.

2023-06-28 18:40 UTC, yuvipanda commented
AMAZING, THANK YOU SO MUCH @mathbunnyru!

2023-06-28 18:50 UTC, mathbunnyru commented
> AMAZING, THANK YOU SO MUCH @mathbunnyru!

You're welcome:)

If you have some spare time, it would be great to have a Julia installation script put to `jupyter/minimal-notebook`, so we don't duplicate big chunks of code in Dockerfiles.

2023-07-25 20:16 UTC, mathbunnyru commented on .github/workflows/docker.yml
> +            julia-notebook,
We forgot to add a new `julia` dependency in `needs:` in a few lines below.

2023-07-25 20:16 UTC, mathbunnyru commented on .github/workflows/docker.yml
> +            julia-notebook,
We forgot to add a new `julia` dependency in `needs:` in a few lines below.

2023-07-25 20:18 UTC, mathbunnyru commented
@yuvipanda I left these comments because I use this image as an example of how a new image can be added.
If you can, please cherry-pick this commit to your branch (so, this PR will be 100% correct).
If not, just ignore this message 🙂

2023-07-25 20:35 UTC, yuvipanda commented
@mathbunnyru that's so sweet! I've cherry-picked that commit but it doesn't seem to be reflected here.

2023-07-25 20:39 UTC, mathbunnyru commented
Thanks @yuvipanda
It seems to be GitHub limitations, so we can't do anything here, unfortunately.
Thanks for trying 🙂