Dummy PR to get CI workflows to run
jupyter/docker-stacks pull request #2087
Opened 2024-01-21 14:22 UTC by manics

2024-01-21 16:03 UTC, mathbunnyru commented on images/docker-stacks-foundation/start.sh
> +# should no longer be specified in CMD
```suggestion
# Backwards compatibility: `start.sh` is executed by default in ENTRYPOINT
# so it should no longer be specified in CMD
```

2024-01-21 16:04 UTC, mathbunnyru commented on tests/docker-stacks-foundation/test_user_options.py
> +def test_startsh_multiple_exec(container: TrackedContainer) -> None:
Thank you for adding a test 👍

2024-01-21 16:09 UTC, mathbunnyru commented on tests/docker-stacks-foundation/test_user_options.py
> +def test_startsh_multiple_exec(container: TrackedContainer) -> None:
Fixed it as well 🙂

2024-01-21 16:12 UTC, mathbunnyru commented
Just to be sure - you searched for all the occurrences of `start.sh` and either removed them (most likely in tests) or rephrased them (mostly in docs)?

2024-01-21 18:01 UTC, manics commented
I missed one mention, fixed in the last commit.

2024-01-21 18:08 UTC, mathbunnyru requested changes

2024-01-21 18:08 UTC, mathbunnyru commented on tests/docker-stacks-foundation/test_python_version.py
> +    python = logs.splitlines()[7]
I don't really like hardcoding line number. Any log line added or removed from `start.sh` will break this test for no reason.

To solve this, for example, we can choose the line which starts with `Python ` instead.

The same thing is true for the test below.

2024-01-21 18:18 UTC, manics commented
I've worked out what's causing the test to fail. Previously start-notebook.py ran start.sh ...., now it's the other way around, so now the output is
```
Entered start.sh with args: start-notebook.py
```
and start-notebook.py runs `jupyter lab`, but doesn't log it

2024-01-21 18:46 UTC, mathbunnyru commented on tests/docker-stacks-foundation/test_python_version.py
> +    python = next(line for line in logs.splitlines() if line.startswith("Python "))
I think I simplified this line so it stays quite readable and is still robust to logging changes in start.sh

2024-01-21 18:46 UTC, mathbunnyru commented on tests/docker-stacks-foundation/test_python_version.py
> +    assert f"python {EXPECTED_PYTHON_VERSION}.*" in logs
Let's have the simplest check possible here, should be just fine for our purposes.

2024-01-21 18:49 UTC, mathbunnyru approved these changes
Overall, great job, @manics, thank you :heart:

I will merge this when tests pass.

2024-01-21 21:20 UTC, yuvipanda commented
NICE!

2024-01-22 04:47 UTC, merged

2024-01-23 13:33 UTC, mathbunnyru commented
@manics @minrk @yuvipanda I merged this 2 days ago, and it seems to work well 👍
I think, there might be some workarounds in the jupyterhub projects, which might no longer be needed, but I am not sure.

@manics, thank you for this PR, it's great.

2024-01-23 13:36 UTC, minrk commented
@mathbunnyru awesome! I think we've mostly removed the workarounds in jupyterhub for more consistent behavior with images not from docker-stacks, so I think this will more directly affect _users_ with a better experience and less configuration required. There are likely docs that should be updated.

2024-03-14 09:53 UTC, consideRatio commented
Wieee this is turning out very helpful right now, thanks to this we can still get the benefits from `start.sh` while overriding CMD for all images to ensure a vulnerable package is upgraded. Super happy to see this already proposed and merged!!