Upgrade to Ubuntu 24.04 Image base
jupyter/docker-stacks pull request #2131
Opened 2024-08-06 22:26 UTC by jmcgrath207

## Describe your changes

- Upgrade to Ubuntu 24.04
- Fix ROOT_CONTAINER ARG in the docker build to allow for custom base image builds.

## Testing.
Ran `DOCKER_BUILD_ARGS='--no-cache make build-all.` All images were built successfully. 

Build Logs ( too big to paste)
https://gist.github.com/jmcgrath207/cf77b5b52cb5c10d45e667ec1052db60

2024-08-07 07:22 UTC, benz0li commented
Cross reference:

* https://github.com/jupyter/docker-stacks/issues/1877

2024-08-11 16:20 UTC, mathbunnyru commented on Makefile
> +	docker build $(DOCKER_BUILD_ARGS) --rm --force-rm --tag "$(REGISTRY)/$(OWNER)/$(notdir $@):latest" "./images/$(notdir $@)" --build-arg REGISTRY="$(REGISTRY)" --build-arg OWNER="$(OWNER)" --build-arg
I know it's slightly annoying, but can you create a separate PR?
This is a bug fix, not a version update, and it makes sense to merge it separately.

2024-08-11 16:21 UTC, mathbunnyru commented on docs/using/selecting.md
> +- OS version like `ubuntu-24.04`
Let's keep this line the same, because it corresponds to the tag mentioned above and we don't actually need to update it

2024-08-11 16:22 UTC, mathbunnyru commented on images/docker-stacks-foundation/Dockerfile
> +    # Delete existing user 'ubuntu' with UID=1000 \
```suggestion
    # Delete existing user 'ubuntu' with UID=1000
```

2024-08-11 16:23 UTC, mathbunnyru commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Ubuntu 24.04
This is unrelated, but we can update it because we expect more users to start ubuntu 24.04 as their host system as well

2024-08-11 16:24 UTC, mathbunnyru commented on .readthedocs.yaml
> +  os: ubuntu-24.04
This is unrelated, please, revert, I usually like to stick to the recommended version in the docs: https://docs.readthedocs.io/en/stable/config-file/v2.html

2024-08-12 14:23 UTC, jmcgrath207 commented
Thanks for the review @mathbunnyru. I have fixed up my PR.

2024-08-12 14:30 UTC, mathbunnyru commented
Thanks.

1. Waiting for a separate PR for `ROOT_CONTAINER` bug as well.
2. This PR is currently waiting for the first point Ubuntu release [per our policy](https://jupyter-docker-stacks.readthedocs.io/en/latest/maintaining/tasks.html#updating-the-ubuntu-base-image). It [should only take 3 days](https://wiki.ubuntu.com/Releases)

2024-08-12 14:45 UTC, jmcgrath207 commented
@mathbunnyru ah, the comment didn't go through.

Here is the root container arg PR.
https://github.com/jupyter/docker-stacks/pull/2133

2024-08-19 11:58 UTC, mathbunnyru commented on .github/workflows/docker-build-test-upload.yml
> +      - name: Pull ubuntu:24.04 image 📥
```suggestion
      - name: Pull base ubuntu image 📥
```

2024-08-19 12:02 UTC, mathbunnyru requested changes

2024-08-19 12:02 UTC, mathbunnyru commented on images/docker-stacks-foundation/Dockerfile
> +    userdel -Rz ubuntu && \
Can you use long options here?

I also think you made a mistake and wanted `-r` (small letter) to remove the home directory and `-Z` (capital letter) to remove SELinux user mapping.

2024-08-19 12:16 UTC, mathbunnyru commented
And one more thing - you need to update `Using old images` table in the root `README.md` file

2024-08-26 12:22 UTC, mathbunnyru commented
Ubuntu 24.04.1 LTS should be released on August 29, 2024

I think this PR is ready to be merged and when this is merged, I will update the README with the latest 22.04 build.

@benz0li could you please take a look here, does it look ok?

2024-08-27 14:33 UTC, benz0li commented
> @benz0li could you please take a look here, does it look ok?

Yes, LGTM.

2024-08-27 16:09 UTC, consideRatio commented
Thank you everyone for your work!! Super happy about these images are available and gets maintained so well!

2024-08-30 09:17 UTC, mathbunnyru commented
Ubuntu 24.04.1 LTS is now available

https://ubuntu.com/blog/upgrade-your-desktop-ubuntu-24-04-lts

2024-08-30 09:18 UTC, mathbunnyru commented
Ubuntu 24.04.1 LTS is now available

https://ubuntu.com/blog/upgrade-your-desktop-ubuntu-24-04-lts

2024-08-30 09:19 UTC, merged